//Branch
export const SINGLE_BRANCH = "SINGLE_BRANCH";
export const GET_BRANCH = "GET_BRANCH";
export const CREATE_BRANCH = "CREATE_BRANCH";
export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const DELETE_BRANCH = "DELETE_BRANCH";

//Degree
export const SINGLE_DEGREE = "SINGLE_DEGREE";
export const GET_DEGREE = "GET_DEGREE";
export const CREATE_DEGREE = "CREATE_DEGREE";
export const UPDATE_DEGREE = "UPDATE_DEGREE";
export const DELETE_DEGREE = "DELETE_DEGREE";

//Semester
export const SINGLE_SEMESTER = "SINGLE_SEMESTER";
export const GET_SEMESTER = "GET_SEMESTER";
export const CREATE_SEMESTER = "CREATE_SEMESTER";
export const UPDATE_SEMESTER = "UPDATE_SEMESTER";
export const DELETE_SEMESTER = "DELETE_SEMESTER";

//Category
export const SINGLE_CATEGORY = "SINGLE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

//Nature of activity
export const SINGLE_NOA = "SINGLE_NOA";
export const GET_NOA = "GET_NOA";
export const CREATE_NOA = "CREATE_NOA";
export const UPDATE_NOA = "UPDATE_NOA";
export const DELETE_NOA = "DELETE_NOA";

//Activity
export const SINGLE_ACTIVITY = "SINGLE_ACTIVITY";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

//Faculty Activity Mapping
export const GET_ACTIVITY_BY_CATEGORY = "GET_ACTIVITY_BY_CATEGORY";
export const GET_ACTIVITY_FACULTY = "GET_ACTIVITY_FACULTY";
export const MAP_ACTIVITY_WITH_FACULTY = "GET_ACTIVITY_BY_CATEGORY";
export const DELETE_ACTIVITY_FACULTY_MAPPING =
  "DELETE_ACTIVITY_FACULTY_MAPPING";

export const GET_BRANCH_WITH_FACULTY = "GET_BRANCH_WITH_FACULTY";

//Activity Document
export const GET_ACTIVITY_DOC = "GET_ACTIVITY_DOC";
export const CREATE_ACTIVITY_DOC = "CREATE_ACTIVITY_DOC";
export const UPDATE_ACTIVITY_DOC = "UPDATE_ACTIVITY_DOC";
export const DELETE_ACTIVITY_DOC = "DELETE_ACTIVITY_DOC";

//Students
export const SINGLE_STUDENT = "SINGLE_STUDENT";
export const GET_STUDENT = "GET_STUDENT";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const GET_VERIFY_STUDENT = "GET_VERIFY_STUDENT";
export const VERIFY_STUDENT = "VERIFY_STUDENT";
export const OVERVIEW_STUDENT = "OVERVIEW_STUDENT";
export const NEXT_SEMESTER = "NEXT_SEMESTER";

//Faculty
export const SINGLE_FACULTY = "SINGLE_FACULTY";
export const GET_FACULTY = "GET_FACULTY";
export const CREATE_FACULTY = "CREATE_FACULTY";
export const UPDATE_FACULTY = "UPDATE_FACULTY";
export const DELETE_FACULTY = "DELETE_FACULTY";
export const GET_VERIFY_FACULTY = "GET_VERIFY_FACULTY";
export const VERIFY_FACULTY = "VERIFY_FACULTY";
export const OVERVIEW_FACULTY = "OVERVIEW_FACULTY";
export const OVERVIEW_ADMIN = "OVERVIEW_ADMIN";

//Faculty Section
export const GET_FACULTY_ACTIVITY = "GET_FACULTY_ACTIVITY";
export const GET_FACULTY_ACTIVITY_STUDENT = "GET_FACULTY_ACTIVITY_STUDENT";
export const DO_FACULTY_ACTIVITY_STUDENT = "DO_FACULTY_ACTIVITY_STUDENT";

//Student Section
export const STUDENT_ENROLL_ACTIVITY = "STUDENT_ENROLL_ACTIVITY";
export const STUDENT_REENROLL_ACTIVITY = "STUDENT_REENROLL_ACTIVITY";
export const STUDENT_CANCEL_ACTIVITY = "STUDENT_CANCEL_ACTIVITY";
export const STUDENT_ACTIVITY_STATUS = "STUDENT_ACTIVITY_STATUS";
export const STUDENT_APPROVED_ACTIVITY = "STUDENT_APPROVED_ACTIVITY";

//Reports
export const GET_ALL_REPORTS = 'GET_ALL_REPORTS';

//Auth
export const USER_LOGIN = "USER_LOGIN";
export const USER_ME = "USER_ME";
export const USER_TOKEN = "USER_TOKEN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_AUTOLOGIN = "USER_AUTOLOGIN";
export const USER_RESET_PASSWORD = "USER_RESET_PASSWORD";
export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD";
